name: ci
run-name: ${{github.job}}-run
on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, synchronize]
    branches:
      - "main"
jobs:
  ci-job:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.17.0"
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
